### Simple Dataset


In [1]:
### Creaing a Dataset class
import torch
from torch.utils.data import Dataset

class toy_set(Dataset):
    def __init__(self, length=100, transform=None):
        self.x = 2*torch.ones(length, 2)
        self.y = torch.ones(length, 1)
        self.len = length
        self.transform = transform
    
    def __getitem__(self, index):
        sample = self.x[index], self.y[index]
        if self.transform:
            sample = self.transform(sample)
        return sample
    
    def __len__(self):
        return self.len

In [4]:
data_set = toy_set()

In [9]:
for i in range(3):
    x, y = data_set[i]
    print('x: ',x, 'y: ', y)

x:  tensor([2., 2.]) y:  tensor([1.])
x:  tensor([2., 2.]) y:  tensor([1.])
x:  tensor([2., 2.]) y:  tensor([1.])


### Transforms

Creating a simple transform class

In [10]:
class add_mul():
    def __init__(self, addx=1, muly=1):
        self.addx = addx
        self.muly = muly
    
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x + self.addx
        y = y*self.muly
        sample = x,y
        return sample


### Directly applying the transfrom method to the datset

In [15]:
data_set = toy_set()
a_m = add_mul()
x_, y_ = a_m(data_set[0])

print(x_, y_)

tensor([3., 3.]) tensor([1.])


### Automatically applying the transform method while creating a dataset object
Including the transfrom method in the constructor

In [16]:
dataset_ = toy_set(transform=a_m)
print(dataset_[0])

(tensor([3., 3.]), tensor([1.]))


Applying multiple transformation at once using `transfroms.Compose`. 

Suppose we add another transformation `mult`

In [18]:
class mult():
    def __init__(self, mul=100):
        self.mul = 100
    
    def __call__(self, sample):
        x = sample[0]
        y = sample[1]
        x = x*self.mul
        y = y*self.mul
        sample = x,y
        return sample

In [22]:
from torchvision import transforms

data_transfrom = transforms.Compose([add_mul(), mult()])

## Applying the transform directly on the data
x_, y_ = data_transfrom(data_set[0])
print(x_, y_)

tensor([300., 300.]) tensor([100.])


### Adding the composed object directly on the dataset.

In [23]:
data_set_tr = toy_set(transform=data_transfrom)
data_set_tr[0]

(tensor([300., 300.]), tensor([100.]))